package usecases.mybatis.model;

public class Hero {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HERO.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HERO.FACTION
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private String faction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.HERO.NAME
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HERO.ID
     *
     * @return the value of PUBLIC.HERO.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HERO.ID
     *
     * @param id the value for PUBLIC.HERO.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HERO.FACTION
     *
     * @return the value of PUBLIC.HERO.FACTION
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public String getFaction() {
        return faction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HERO.FACTION
     *
     * @param faction the value for PUBLIC.HERO.FACTION
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setFaction(String faction) {
        this.faction = faction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.HERO.NAME
     *
     * @return the value of PUBLIC.HERO.NAME
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.HERO.NAME
     *
     * @param name the value for PUBLIC.HERO.NAME
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}