package usecases.mybatis.model;

public class Skill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SKILL.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SKILL.DESCRIPTION
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SKILL.LEVELREQUIREMENT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Byte levelrequirement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SKILL.NAME
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SKILL.ID
     *
     * @return the value of PUBLIC.SKILL.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SKILL.ID
     *
     * @param id the value for PUBLIC.SKILL.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SKILL.DESCRIPTION
     *
     * @return the value of PUBLIC.SKILL.DESCRIPTION
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SKILL.DESCRIPTION
     *
     * @param description the value for PUBLIC.SKILL.DESCRIPTION
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SKILL.LEVELREQUIREMENT
     *
     * @return the value of PUBLIC.SKILL.LEVELREQUIREMENT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Byte getLevelrequirement() {
        return levelrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SKILL.LEVELREQUIREMENT
     *
     * @param levelrequirement the value for PUBLIC.SKILL.LEVELREQUIREMENT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setLevelrequirement(Byte levelrequirement) {
        this.levelrequirement = levelrequirement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SKILL.NAME
     *
     * @return the value of PUBLIC.SKILL.NAME
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SKILL.NAME
     *
     * @param name the value for PUBLIC.SKILL.NAME
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setName(String name) {
        this.name = name;
    }
}