package usecases.mybatis.model;

public class Stat {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAT.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAT.ATTACK
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Short attack;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAT.COLOR
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAT.HEALTH
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Short health;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAT.THREAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Short threat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STAT.CREATURE_ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    private Integer creatureId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAT.ID
     *
     * @return the value of PUBLIC.STAT.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAT.ID
     *
     * @param id the value for PUBLIC.STAT.ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAT.ATTACK
     *
     * @return the value of PUBLIC.STAT.ATTACK
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Short getAttack() {
        return attack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAT.ATTACK
     *
     * @param attack the value for PUBLIC.STAT.ATTACK
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setAttack(Short attack) {
        this.attack = attack;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAT.COLOR
     *
     * @return the value of PUBLIC.STAT.COLOR
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAT.COLOR
     *
     * @param color the value for PUBLIC.STAT.COLOR
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAT.HEALTH
     *
     * @return the value of PUBLIC.STAT.HEALTH
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Short getHealth() {
        return health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAT.HEALTH
     *
     * @param health the value for PUBLIC.STAT.HEALTH
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setHealth(Short health) {
        this.health = health;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAT.THREAT
     *
     * @return the value of PUBLIC.STAT.THREAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Short getThreat() {
        return threat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAT.THREAT
     *
     * @param threat the value for PUBLIC.STAT.THREAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setThreat(Short threat) {
        this.threat = threat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STAT.CREATURE_ID
     *
     * @return the value of PUBLIC.STAT.CREATURE_ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public Integer getCreatureId() {
        return creatureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STAT.CREATURE_ID
     *
     * @param creatureId the value for PUBLIC.STAT.CREATURE_ID
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    public void setCreatureId(Integer creatureId) {
        this.creatureId = creatureId;
    }
}