package usecases.mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.mybatis.cdi.Mapper;
import usecases.mybatis.model.Stat;
@Mapper
public interface StatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Delete({
        "delete from PUBLIC.STAT",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Insert({
        "insert into PUBLIC.STAT (ATTACK, COLOR, ",
        "HEALTH, THREAT, ",
        "CREATURE_ID)",
        "values (#{attack,jdbcType=SMALLINT}, #{color,jdbcType=VARCHAR}, ",
        "#{health,jdbcType=SMALLINT}, #{threat,jdbcType=SMALLINT}, ",
        "#{creatureId,jdbcType=INTEGER})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Stat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, ATTACK, COLOR, HEALTH, THREAT, CREATURE_ID",
        "from PUBLIC.STAT",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ATTACK", property="attack", jdbcType=JdbcType.SMALLINT),
        @Result(column="COLOR", property="color", jdbcType=JdbcType.VARCHAR),
        @Result(column="HEALTH", property="health", jdbcType=JdbcType.SMALLINT),
        @Result(column="THREAT", property="threat", jdbcType=JdbcType.SMALLINT),
        @Result(column="CREATURE_ID", property="creatureId", jdbcType=JdbcType.INTEGER)
    })
    Stat selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, ATTACK, COLOR, HEALTH, THREAT, CREATURE_ID",
        "from PUBLIC.STAT"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ATTACK", property="attack", jdbcType=JdbcType.SMALLINT),
        @Result(column="COLOR", property="color", jdbcType=JdbcType.VARCHAR),
        @Result(column="HEALTH", property="health", jdbcType=JdbcType.SMALLINT),
        @Result(column="THREAT", property="threat", jdbcType=JdbcType.SMALLINT),
        @Result(column="CREATURE_ID", property="creatureId", jdbcType=JdbcType.INTEGER)
    })
    List<Stat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STAT
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Update({
        "update PUBLIC.STAT",
        "set ATTACK = #{attack,jdbcType=SMALLINT},",
          "COLOR = #{color,jdbcType=VARCHAR},",
          "HEALTH = #{health,jdbcType=SMALLINT},",
          "THREAT = #{threat,jdbcType=SMALLINT},",
          "CREATURE_ID = #{creatureId,jdbcType=INTEGER}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Stat record);

    @Select("SELECT * FROM PUBLIC.STAT WHERE CREATURE_ID = #{creatureId}")
    @Results(value = {
            @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
            @Result(column="ATTACK", property="attack", jdbcType=JdbcType.SMALLINT),
            @Result(column="COLOR", property="color", jdbcType=JdbcType.VARCHAR),
            @Result(column="HEALTH", property="health", jdbcType=JdbcType.SMALLINT),
            @Result(column="THREAT", property="threat", jdbcType=JdbcType.SMALLINT),
            @Result(column="CREATURE_ID", property="creatureId", jdbcType=JdbcType.INTEGER)
    })
    public List<Stat> selectAllByCreaturePrimaryKey(int creatureId);
}