package mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.mybatis.cdi.Mapper;
import mybatis.model.Creature;

@Mapper
public interface CreatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CREATURE
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Delete({
        "delete from PUBLIC.CREATURE",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CREATURE
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Insert({
        "insert into PUBLIC.CREATURE (NAME)",
        "values (#{name,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Creature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CREATURE
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, NAME",
        "from PUBLIC.CREATURE",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR)
    })
    Creature selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CREATURE
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, NAME",
        "from PUBLIC.CREATURE"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<Creature> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CREATURE
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Update({
        "update PUBLIC.CREATURE",
        "set NAME = #{name,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Creature record);
}