package mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.mybatis.cdi.Mapper;
import mybatis.model.Hero;
@Mapper
public interface HeroMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HERO
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Delete({
        "delete from PUBLIC.HERO",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HERO
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Insert({
        "insert into PUBLIC.HERO (FACTION, NAME)",
        "values (#{faction,jdbcType=VARCHAR}, #{name,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Hero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HERO
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, FACTION, NAME",
        "from PUBLIC.HERO",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FACTION", property="faction", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR)
    })
    Hero selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HERO
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, FACTION, NAME",
        "from PUBLIC.HERO"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="FACTION", property="faction", jdbcType=JdbcType.VARCHAR),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<Hero> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HERO
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Update({
        "update PUBLIC.HERO",
        "set FACTION = #{faction,jdbcType=VARCHAR},",
          "NAME = #{name,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Hero record);
}