package mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.type.JdbcType;
import org.mybatis.cdi.Mapper;
import mybatis.model.HeroSkill;
@Mapper
public interface HeroSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HERO_SKILL
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Insert({
        "insert into PUBLIC.HERO_SKILL (HEROES_ID, SKILLS_ID)",
        "values (#{heroesId,jdbcType=INTEGER}, #{skillsId,jdbcType=INTEGER})"
    })
    int insert(HeroSkill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.HERO_SKILL
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "HEROES_ID, SKILLS_ID",
        "from PUBLIC.HERO_SKILL"
    })
    @Results({
        @Result(column="HEROES_ID", property="heroesId", jdbcType=JdbcType.INTEGER),
        @Result(column="SKILLS_ID", property="skillsId", jdbcType=JdbcType.INTEGER)
    })
    List<HeroSkill> selectAll();
}