package mybatis.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.mybatis.cdi.Mapper;
import mybatis.model.Skill;
@Mapper
public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SKILL
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Delete({
        "delete from PUBLIC.SKILL",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SKILL
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Insert({
        "insert into PUBLIC.SKILL (DESCRIPTION, LEVELREQUIREMENT, ",
        "NAME)",
        "values (#{description,jdbcType=VARCHAR}, #{levelrequirement,jdbcType=TINYINT}, ",
        "#{name,jdbcType=VARCHAR})"
    })
    @Options(useGeneratedKeys=true,keyProperty="id")
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SKILL
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, DESCRIPTION, LEVELREQUIREMENT, NAME",
        "from PUBLIC.SKILL",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEVELREQUIREMENT", property="levelrequirement", jdbcType=JdbcType.TINYINT),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR)
    })
    Skill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SKILL
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Select({
        "select",
        "ID, DESCRIPTION, LEVELREQUIREMENT, NAME",
        "from PUBLIC.SKILL"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="DESCRIPTION", property="description", jdbcType=JdbcType.VARCHAR),
        @Result(column="LEVELREQUIREMENT", property="levelrequirement", jdbcType=JdbcType.TINYINT),
        @Result(column="NAME", property="name", jdbcType=JdbcType.VARCHAR)
    })
    List<Skill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SKILL
     *
     * @mbg.generated Fri Mar 08 22:23:27 EET 2019
     */
    @Update({
        "update PUBLIC.SKILL",
        "set DESCRIPTION = #{description,jdbcType=VARCHAR},",
          "LEVELREQUIREMENT = #{levelrequirement,jdbcType=TINYINT},",
          "NAME = #{name,jdbcType=VARCHAR}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Skill record);
}